### PR TITLE
changed router annotation to be compatible with shopware version 6.5.*

### PR DESCRIPTION
**Pull request by fibenacci**
this change added the new annotation structure to be compatibe with future versions of shopware 6.5.*

### CODE REVIEW

**Comment by tinect** [comment]
Would you please adjust the minimum version in composer.json to fit your changes?

**Comment by fibenacci** [comment]
@tinect i've adjusted the minimum version

**Comment by tinect** [comment]
@fibenacci just noticed that it won't work anyway with the adjustments, does it on your side?

**Comment by tinect** [comment]
I decided to archive this plugin. Please use the configuration of the web server.

**Pull request closed without merging**
